Repository tuva-health/tuva, pull requests merged in 2023-08, with the labels that each got.

#178 Add "Quality Measures Reporting" mart with Breast Cancer Screening
  dbt_project.yml
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  models/quality_measures_reporting/final/quality_measures_reporting__summary_counts.sql
  models/quality_measures_reporting/final/quality_measures_reporting__summary_long.sql
  models/quality_measures_reporting/final/quality_measures_reporting__summary_wide.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_denominator.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_advanced_illness.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_dementia.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_hospice.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_institutional.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_mastectomy.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclude_palliative.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_exclusions.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_long.sql
  models/quality_measures_reporting/intermediate/quality_measures_reporting__int_nqf2372_numerator.sql
  models/quality_measures_reporting/quality_measures_reporting_models.yml
  models/quality_measures_reporting/staging/quality_measures_reporting__stg_core__condition.sql
  models/quality_measures_reporting/staging/quality_measures_reporting__stg_core__patient.sql
  models/quality_measures_reporting/staging/quality_measures_reporting__stg_core__procedure.sql
  models/quality_measures_reporting/staging/quality_measures_reporting__stg_medical_claim.sql
  models/quality_measures_reporting/staging/quality_measures_reporting__stg_pharmacy_claim.sql
  seeds/value_sets/quality_measures_reporting/quality_measures_reporting__concepts.csv
  seeds/value_sets/quality_measures_reporting/quality_measures_reporting__measures.csv
  seeds/value_sets/quality_measures_reporting/quality_measures_reporting__value_sets.csv
  seeds/value_sets/quality_measures_reporting/quality_measures_reporting_seeds.yml
Labels: enhancement, data-mart

#180 Provider terminology update
  dbt_project.yml
  models/acute_inpatient/final/acute_inpatient__summary.sql
  seeds/terminology/terminology__provider.csv
  seeds/terminology/terminology_seeds.yml
Labels: enhancement

#179 Add demo synthetic dataset as part of integration_tests in core package
  CONTRIBUTING.md
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  integration_tests/models/_sources.yml
  integration_tests/models/eligibility.sql
  integration_tests/models/medical_claim.sql
  integration_tests/models/pharmacy_claim.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/eligibility_seed.csv
  integration_tests/seeds/medical_claim_seed.csv
  integration_tests/seeds/pharmacy_claim_seed.csv
  macros/load_seed.sql
  models/ccsr/ccsr_models.yml
Labels: enhancement, community

#185 Add databricks support
  README.md
  dbt_project.yml
  macros/load_seed.sql
  seeds/terminology/terminology_seeds.yml
  seeds/value_sets/ccsr/ccsr_seeds.yml
  seeds/value_sets/cms_hcc/cms_hcc_seeds.yml
  seeds/value_sets/data_profiling/data_profiling__seeds.yml
  seeds/value_sets/quality_measures_reporting/quality_measures_reporting_seeds.yml
  seeds/value_sets/readmissions/readmissions_seeds.yml
Labels: enhancement, community
