Repository tuva-health/tuva, pull requests merged in 2023-05, with the labels that each got.

#75 Cc schema and dbt version
  dbt_project.yml
  models/chronic_conditions/cms_chronic_conditions_models.yml
  models/chronic_conditions/tuva_chronic_conditions_models.yml
  seeds/value_sets/readmissions/readmissions_seeds.yml
Labels: bug

#78 added icd-9 file and updated YAML
  seeds/terminology/terminology__icd_9_cm.csv
  seeds/terminology/terminology_seeds.yml
Labels: enhancement

#89 [FIXED] Path to provider seeds for post-hook
  dbt_project.yml
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  models/input_layer/input_layer__models.yml
Labels: bug

#94 updated pmpm to use new service category grouper logic
  dbt_project.yml
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  integration_tests/models/eligibility.sql
  integration_tests/models/medical_claim.sql
  integration_tests/models/pharmacy_claim.sql
  models/member_months/final/member_months.sql
  models/member_months/member_months_models.yml
  models/pmpm/final/pmpm__pmpm.sql
  models/pmpm/final/pmpm__pmpm_builder.sql
  models/pmpm/final/pmpm__pmpm_prep.sql
  models/pmpm/final/pmpm__pmpm_trends.sql
  models/pmpm/intermediate/pmpm__claim_spend_and_utilization.sql
  models/pmpm/intermediate/pmpm__member_month_count.sql
  models/pmpm/intermediate/pmpm__patient_spend_with_service_categories.sql
  models/pmpm/intermediate/pmpm__pmpm_output.sql
  models/pmpm/intermediate/pmpm__service_category_1_allowed_pivot.sql
  models/pmpm/intermediate/pmpm__service_category_1_paid_pivot.sql
  models/pmpm/intermediate/pmpm__service_category_2_allowed_pivot.sql
  models/pmpm/intermediate/pmpm__service_category_2_paid_pivot.sql
  models/pmpm/pmpm_models.yml
  models/service_category_grouper/final/service_category__service_category_grouper.sql
  seeds/value_sets/service_categories/service_categories_seeds.yml
  seeds/value_sets/service_categories/service_category__service_categories.csv
Labels: data-mart

#97 Service category gropuer DQ models building under wrong schema
  dbt_project.yml
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  models/service_category_grouper/service_category_models.yml
Labels: bug
