Repository tuva-health/tuva, pull requests merged in 2023-10, with the labels that each got.

#254 removed redundant PII fields
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  models/core/staging/core__stg_claims_eligibility.sql
Labels: enhancement

#263 Creating Emergency Department Encounters
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/models/eligibility.sql
  integration_tests/docs_generate/models/encounter.sql
  models/ccsr/ccsr_models.yml
  models/ccsr/final/ccsr__wide_condition_category.sql
  models/ccsr/final/ccsr__wide_procedure_category.sql
  models/claims_preprocessing/acute_inpatient/final/acute_inpatient__summary.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__encounter_id.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__encounter_start_and_end_dates.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__first_claim_values.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__last_claim_values.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__professional_encounter_id.sql
  models/claims_preprocessing/acute_inpatient/staging/acute_inpatient__stg_service_category.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/claims_preprocessing/emergency_department/final/emergency_department__summary.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_encounter_id.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_encounter_start_and_end_dates.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_first_claim_values.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_institutional_claims.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_institutional_encounter_id.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_last_claim_values.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_professional_encounter_id.sql
  models/claims_preprocessing/service_category/final/service_category__service_category_grouper.sql
  models/claims_preprocessing/service_category/intermediate/service_category__emergency_department_institutional.sql
  models/core/core_models.yml
  models/core/staging/core__stg_claims_condition.sql
  models/core/staging/core__stg_claims_eligibility.sql
  models/core/staging/core__stg_claims_encounter.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_procedure.sql
  models/core/staging/core__stg_clinical_encounter.sql
  models/ed_classification/data_quality/ed_classification__claim_categorization.sql
  models/ed_classification/data_quality/ed_classification__unclassified_conditions.sql
  models/ed_classification/data_quality/ed_classification__unclassified_rows.sql
  models/ed_classification/ed_classification_models.yml
  models/ed_classification/final/ed_classification__summary.sql
  models/ed_classification/intermediate/ed_classification__int_by_ccs_description.sql
  models/ed_classification/intermediate/ed_classification__int_by_patient_race.sql
  models/ed_classification/intermediate/ed_classification__int_by_provider_parent_organization.sql
  models/ed_classification/intermediate/ed_classification__int_by_provider_practice_state.sql
  models/ed_classification/intermediate/ed_classification__int_by_year.sql
  models/ed_classification/intermediate/ed_classification__int_by_year_month.sql
  models/ed_classification/intermediate/ed_classification__int_condition_with_claim.sql
  models/ed_classification/intermediate/ed_classification__int_filter_encounter_with_classification.sql
  models/ed_classification/intermediate/ed_classification__int_map_primary_dx.sql
  models/ed_classification/intermediate/ed_classification__int_patient_list.sql
  models/ed_classification/intermediate/ed_classification__int_primary_dx_per_claim.sql
  models/ed_classification/staging/ed_classification__stg_condition.sql
  models/ed_classification/staging/ed_classification__stg_encounter.sql
  models/ed_classification/staging/ed_classification__stg_medical_claim.sql
  models/ed_classification/staging/ed_classification__stg_patient.sql
Labels: bug, enhancement

#266 Add nqf0034 colorectal screening
  docs/catalog.json
  docs/index.html
  docs/manifest.json
  docs/run_results.json
  integration_tests/seeds/medical_claim_seed.csv
  models/quality_measures/final/quality_measures__summary_long.sql
  models/quality_measures/final/quality_measures__summary_wide.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034__frailty.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034__performance_period.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_denominator.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_advanced_illness.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_colectomy_cancer.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_dementia.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_hospice_palliative.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_institutional_snp.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclusions.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_long.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_numerator.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_denominator.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_advanced_illness.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_dementia.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_hospice.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_institutional.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_mastectomy.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_palliative.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclusions.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_long.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_numerator.sql
  models/quality_measures/quality_measures_models.yml
  models/quality_measures/staging/quality_measures__stg_core__lab_result.sql
  models/quality_measures/staging/quality_measures__stg_medical_claim.sql
  models/quality_measures/staging/quality_measures__stg_pharmacy_claim.sql
  seeds/value_sets/quality_measures/quality_measures__concepts.csv
  seeds/value_sets/quality_measures/quality_measures__measures.csv
  seeds/value_sets/quality_measures/quality_measures__value_sets.csv
Labels: enhancement

#268 Readmissions dx1 fix
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  models/readmissions/final/readmissions__encounter_augmented.sql
  models/readmissions/intermediate/readmissions__diagnosis.sql
  models/readmissions/intermediate/readmissions__diagnosis_ccs.sql
  models/readmissions/intermediate/readmissions__encounter.sql
  models/readmissions/intermediate/readmissions__encounter_data_quality.sql
  models/readmissions/intermediate/readmissions__encounter_specialty_cohort.sql
  models/readmissions/intermediate/readmissions__encounter_with_ccs.sql
  models/readmissions/intermediate/readmissions__exclusion.sql
  models/readmissions/intermediate/readmissions__planned_encounter.sql
  models/readmissions/intermediate/readmissions__primary_diagnosis_count.sql
  models/readmissions/readmissions_models.yml
  models/readmissions/staging/readmissions__stg_core__encounter.sql
Labels: bug
