Repository tuva-health/tuva, pull requests merged in 2023-09, with the labels that each got.

#201 Cast core stage data types
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/macros/try_to_cast_date.sql
  integration_tests/models/condition.sql
  integration_tests/models/encounter.sql
  integration_tests/models/lab_result.sql
  integration_tests/models/location.sql
  integration_tests/models/medication.sql
  integration_tests/models/observation.sql
  integration_tests/models/patient.sql
  integration_tests/models/practitioner.sql
  integration_tests/models/procedure.sql
  macros/try_to_cast_date.sql
  models/core/staging/core__stg_claims_condition.sql
  models/core/staging/core__stg_claims_encounter.sql
  models/core/staging/core__stg_claims_location.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_patient.sql
  models/core/staging/core__stg_claims_practitioner.sql
  models/core/staging/core__stg_claims_procedure.sql
  models/core/staging/core__stg_clinical_condition.sql
  models/core/staging/core__stg_clinical_encounter.sql
  models/core/staging/core__stg_clinical_lab_result.sql
  models/core/staging/core__stg_clinical_location.sql
  models/core/staging/core__stg_clinical_medication.sql
  models/core/staging/core__stg_clinical_observation.sql
  models/core/staging/core__stg_clinical_patient.sql
  models/core/staging/core__stg_clinical_practitioner.sql
  models/core/staging/core__stg_clinical_procedure.sql
Labels: enhancement

#204 Add ed classification mart
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  models/ed_classification/data_quality/ed_classification__claim_categorization.sql
  models/ed_classification/data_quality/ed_classification__unclassified_conditions.sql
  models/ed_classification/data_quality/ed_classification__unclassified_rows.sql
  models/ed_classification/ed_classification_models.yml
  models/ed_classification/final/ed_classification__summary.sql
  models/ed_classification/intermediate/ed_classification__int_by_ccs_description.sql
  models/ed_classification/intermediate/ed_classification__int_by_patient_race.sql
  models/ed_classification/intermediate/ed_classification__int_by_provider_parent_organization.sql
  models/ed_classification/intermediate/ed_classification__int_by_provider_practice_state.sql
  models/ed_classification/intermediate/ed_classification__int_by_year.sql
  models/ed_classification/intermediate/ed_classification__int_by_year_month.sql
  models/ed_classification/intermediate/ed_classification__int_condition_with_claim.sql
  models/ed_classification/intermediate/ed_classification__int_condition_with_class.sql
  models/ed_classification/intermediate/ed_classification__int_merge_condition.sql
  models/ed_classification/intermediate/ed_classification__int_patient_list.sql
  models/ed_classification/intermediate/ed_classification__int_primary_dx_per_claim.sql
  models/ed_classification/staging/ed_classification__stg_condition.sql
  models/ed_classification/staging/ed_classification__stg_encounter.sql
  models/ed_classification/staging/ed_classification__stg_medical_claim.sql
  models/ed_classification/staging/ed_classification__stg_patient.sql
  seeds/value_sets/ed_classification/ed_classification__categories.csv
  seeds/value_sets/ed_classification/ed_classification__icd_10_cm_to_ccs.csv
  seeds/value_sets/ed_classification/ed_classification__johnston_icd10.csv
  seeds/value_sets/ed_classification/ed_classification__johnston_icd9.csv
  seeds/value_sets/ed_classification/ed_classification_seeds.yml
Labels: enhancement

#210 Service category bug 208
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  models/claims_preprocessing/service_category/final/service_category__service_category_grouper.sql
Labels: bug

#211 New Loinc Terminology
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  seeds/terminology/terminology__icd_9_cm.csv
  seeds/terminology/terminology__loinc.csv
  seeds/terminology/terminology__loinc_deprecated_mapping.csv
  seeds/terminology/terminology_seeds.yml
Labels: enhancement

#221 Remove hard-coded table reference in Service Category Grouper
  dbt_project.yml
  models/claims_preprocessing/service_category/final/service_category__service_category_grouper.sql
Labels: bug

#222 Ed classification bugfix
  dbt_project.yml
  models/ed_classification/ed_classification_models.yml
  models/ed_classification/staging/ed_classification__stg_condition.sql
  models/ed_classification/staging/ed_classification__stg_encounter.sql
  models/ed_classification/staging/ed_classification__stg_medical_claim.sql
  models/ed_classification/staging/ed_classification__stg_patient.sql
Labels: bug

#223 Add original_reason_entitlement_code to Eligibility
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/eligibility.sql
  integration_tests/models/_claims__models.yml
  integration_tests/models/_integration_tests__models.yml
  integration_tests/models/_sources.yml
  integration_tests/models/eligibility.sql
  integration_tests/models/medical_claim.sql
  integration_tests/models/pharmacy_claim.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/eligibility_seed.csv
  models/claims_preprocessing/data_profiling/intermediate/data_profiling__eligibility_denominators.sql
  models/claims_preprocessing/data_profiling/intermediate/data_profiling__eligibility_invalid_values.sql
  models/core/core_models.yml
  models/core/staging/core__stg_claims_eligibility.sql
  seeds/terminology/terminology__medicare_orec.csv
  seeds/terminology/terminology_seeds.yml
Labels: bug, core-data-model

#228 fixed missing amount fields in encounter
  models/claims_preprocessing/acute_inpatient/final/acute_inpatient__summary.sql
Labels: bug

#226 Resolution of issues 215 and 224
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  models/claims_preprocessing/acute_inpatient/staging/acute_inpatient__stg_service_category.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/core/staging/core__stg_claims_patient.sql
  seeds/value_sets/data_profiling/data_profiling__seeds.yml
  seeds/value_sets/service_categories/service_categories_seeds.yml
Labels: bug

#235 patch for acute inpatient
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__institutional_claims.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__professional_encounter_id.sql
Labels: bug

#239 Fix readmission summary column
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/models/eligibility.sql
  integration_tests/docs_generate/models/medical_claim.sql
  integration_tests/docs_generate/models/pharmacy_claim.sql
  models/readmissions/final/readmissions__encounter_augmented.sql
  models/readmissions/final/readmissions__readmission_summary.sql
  models/readmissions/intermediate/readmissions__encounter.sql
  models/readmissions/staging/readmissions__stg_core__encounter.sql
Labels: data-mart

#247 Issue Fixes 237, 245, and 246
  models/ccsr/final/ccsr__long_condition_category.sql
  models/ccsr/final/ccsr__long_procedure_category.sql
  models/ccsr/final/ccsr__singular_condition_category.sql
  models/ccsr/final/ccsr__wide_condition_category.sql
  models/ccsr/final/ccsr__wide_procedure_category.sql
  models/ccsr/intermediate/ccsr__dx_vertical_pivot.sql
  models/ccsr/intermediate/ccsr__procedure_category_map.sql
  models/ccsr/staging/ccsr__stg_core__condition.sql
  models/ccsr/staging/ccsr__stg_core__procedure.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/financial_pmpm/intermediate/financial_pmpm__patient_spend_with_service_categories.sql
Labels: bug, enhancement
