Repository tuva-health/tuva, pull requests merged in 2024-07, with the labels that each got.

#524 bug fix for multiple org names in one encounter
  models/claims_preprocessing/acute_inpatient/final/acute_inpatient__summary.sql
  models/claims_preprocessing/emergency_department/final/emergency_department__summary.sql
Labels: bug

#523 Seed checking quoting
  macros/get_selected_seeds.sql
Labels: bug

#533 Hcc analytics updates
  models/core/core_models.yml
  models/core/staging/core__stg_claims_patient.sql
  models/core/staging/core__stg_clinical_patient.sql
  models/data_quality/mart_review/final/mart_review__patient.sql
Labels: enhancement, core-data-model

#534 fixing bug with pqi data type
  models/ahrq_measures/pqi/final/ahrq_measures__pqi_denom_long.sql
  models/ahrq_measures/pqi/final/ahrq_measures__pqi_num_long.sql
  models/data_quality/mart_review/final/mart_review__ed_classification.sql
  models/pharmacy/staging/pharmacy__stg_pharmacy_claim.sql
Labels: bug

#539 Databricks load seed syntax fix
  macros/load_seed.sql
Labels: enhancement

#538 Pharmacy PMPM date change
  models/financial_pmpm/intermediate/financial_pmpm__patient_spend_with_service_categories.sql
  models/financial_pmpm/staging/financial_pmpm__stg_pharmacy_claim.sql
Labels: enhancement

#548 Bug Fixes: Data Quality and CCSR
  models/ccsr/ccsr_models.yml
  models/ccsr/final/ccsr__long_procedure_category.sql
  models/ccsr/staging/ccsr__stg_core__procedure.sql
  models/data_quality/intermediate/union_processing/claims/data_quality__claim_type_summary.sql
Labels: bug

#545 Quality Measure CBE0101 Falls: Plan of Care
  models/quality_measures/final/quality_measures__summary_long.sql
  models/quality_measures/final/quality_measures__summary_wide.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101__performance_period.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_denominator.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_exclusions.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_long.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_numerator.sql
  models/quality_measures/quality_measures_models.yml
  models/quality_measures/staging/quality_measures__stg_core__procedure.sql
  models/quality_measures/staging/quality_measures__stg_medical_claim.sql
Labels: enhancement

#550 Procedure Codes Inclusion in Quality Measure CQM236 Numerator
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_numerator.sql
Labels: bug

#559 Eligibility pk bug
  models/core/staging/core__stg_claims_eligibility.sql
Labels: bug
