Repository tuva-health/tuva, pull requests merged in 2024-10, with the labels that each got.

#594 fix the space in the generated schema name template
  models/pharmacy/pharmacy_models.yml
Labels: bug

#599 Doc blocks
  dbt_project.yml
  docs/column_descriptions.md
  models/claims_preprocessing/encounters/encounter_models.yml
Labels: docs, enhancement

#605 added new data quality models
  models/data_quality/data_quality_models.yml
  models/data_quality/intermediate/data_quality__dx_and_px.sql
  models/data_quality/intermediate/data_quality__medical_claim_date_trends.sql
Labels: enhancement

#621 Ci outside contributor fixes
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
  ci_testing/profiles/fabric/profiles.yml
  ci_testing/profiles/redshift/profiles.yml
  ci_testing/profiles/snowflake/profiles.yml
  integration_tests/dbt_project.yml
  macros/limit_zero.sql
  models/data_quality/dqi/intermediate/union_processing/claims/data_quality__claim_type_summary.sql
Labels: enhancement

#624 fixed schema typo
  models/normalize/_models.yml
Labels: bug

#626 updating gitignore for .envrc
  .gitignore
Labels: ignore-for-release

#632 added safe cast for obs+lab result eval
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_numerator.sql
Labels: enhancement

#634 updating config logic for when the provider_attribution.sql model runs
  integration_tests/models/provider_attribution.sql
Labels: bug, ignore-for-release

#637 Fix limit logic in financial_pmpm__stg_provider_attribution
  models/financial_pmpm/staging/financial_pmpm__stg_provider_attribution.sql
Labels: bug

#636 Fixed Spelling
  models/data_quality/data_quality_models.yml
  models/data_quality/final/data_quality__analytics_reference_summary.sql
  models/data_quality/intermediate/data_quality__acute_inpatient_prevalence.sql
Labels: bug
