Repository tuva-health/tuva, pull requests merged in 2024-06, with the labels that each got.

#495 CMS HCC seed update
  dbt_project.yml
  seeds/value_sets/cms_hcc/cms_hcc_seeds.yml
Labels: bug

#496 updated test data vars
  .gitignore
  ci_testing/docs_generate/dbt_project.yml
  ci_testing/docs_generate/docs/overview.md
  ci_testing/docs_generate/models/_models.yml
  ci_testing/docs_generate/models/condition.sql
  ci_testing/docs_generate/models/eligibility.sql
  ci_testing/docs_generate/models/encounter.sql
  ci_testing/docs_generate/models/lab_result.sql
  ci_testing/docs_generate/models/location.sql
  ci_testing/docs_generate/models/medical_claim.sql
  ci_testing/docs_generate/models/medication.sql
  ci_testing/docs_generate/models/observation.sql
  ci_testing/docs_generate/models/patient.sql
  ci_testing/docs_generate/models/pharmacy_claim.sql
  ci_testing/docs_generate/models/practitioner.sql
  ci_testing/docs_generate/models/procedure.sql
  ci_testing/docs_generate/packages.yml
  integration_tests/.gitignore
  integration_tests/dbt_project.yml
  integration_tests/models/_integration_tests__models.yml
  integration_tests/models/_sources.yml
  integration_tests/models/condition.sql
  integration_tests/models/eligibility.sql
  integration_tests/models/encounter.sql
  integration_tests/models/lab_result.sql
  integration_tests/models/location.sql
  integration_tests/models/medical_claim.sql
  integration_tests/models/medication.sql
  integration_tests/models/observation.sql
  integration_tests/models/patient.sql
  integration_tests/models/pharmacy_claim.sql
  integration_tests/models/practitioner.sql
  integration_tests/models/procedure.sql
  integration_tests/package-lock.yml
  integration_tests/profiles/bigquery/profiles.yml
  integration_tests/profiles/redshift/profiles.yml
  integration_tests/profiles/snowflake/profiles.yml
  integration_tests/seeds/_seeds.yml
  macros/get_selected_seeds.sql
  package-lock.yml
Labels: enhancement

#499 [BUG FIX] Change grain of quality measures summary wide table
  models/quality_measures/final/quality_measures__summary_long.sql
  models/quality_measures/final/quality_measures__summary_wide.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055_long.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_long.sql
  models/quality_measures/intermediate/cqm438_statin_therapy_for_patients_with_cardiovascular_disease/quality_measures__int_cqm438_long.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_long.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_long.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059_long.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_long.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097_long.sql
Labels: bug

#502 Add file identifiers
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/condition.sql
  integration_tests/docs_generate/models/eligibility.sql
  integration_tests/docs_generate/models/encounter.sql
  integration_tests/docs_generate/models/lab_result.sql
  integration_tests/docs_generate/models/location.sql
  integration_tests/docs_generate/models/medical_claim.sql
  integration_tests/docs_generate/models/medication.sql
  integration_tests/docs_generate/models/observation.sql
  integration_tests/docs_generate/models/patient.sql
  integration_tests/docs_generate/models/pharmacy_claim.sql
  integration_tests/docs_generate/models/practitioner.sql
  integration_tests/docs_generate/models/procedure.sql
  integration_tests/models/condition.sql
  integration_tests/models/encounter.sql
  integration_tests/models/location.sql
  integration_tests/models/medication.sql
  integration_tests/models/patient.sql
  integration_tests/models/practitioner.sql
  integration_tests/models/procedure.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/eligibility_seed.csv
  integration_tests/seeds/lab_result_seed.csv
  integration_tests/seeds/medical_claim_seed.csv
  integration_tests/seeds/observation_seed.csv
  integration_tests/seeds/pharmacy_claim_seed.csv
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_eligibility.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_medical_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_pharmacy_claim.sql
Labels: breaking-change

#504 Add member months to core
  models/ahrq_measures/pqi/staging/ahrq_measures__stg_pqi_member_months.sql
  models/cms_hcc/cms_hcc_models.yml
  models/cms_hcc/final/cms_hcc__patient_risk_scores.sql
  models/cms_hcc/staging/cms_hcc__stg_core__member_months.sql
  models/core/core_models.yml
  models/core/final/core__member_months.sql
  models/financial_pmpm/final/financial_pmpm__pmpm_prep.sql
  models/financial_pmpm/financial_pmpm_models.yml
  models/insights/final/insights__count_claim_by_date_column.sql
  models/insights/final/insights__orphan_claim_by_claim_type.sql
Labels: breaking-change

#505 Add in_network_flag
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/medical_claim_seed.csv
  integration_tests/seeds/pharmacy_claim_seed.csv
  models/claims_preprocessing/normalized_input/final/normalized_input__medical_claim.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_medical_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_pharmacy_claim.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
Labels: breaking-change

#497 Implementation of unique tests on all Core models
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/dbt_project.yml
  models/core/core_models.yml
  models/core/staging/core__stg_claims_condition.sql
  models/core/staging/core__stg_claims_eligibility.sql
  models/core/staging/core__stg_claims_location.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
Labels: enhancement

#508 Refactor code and description columns
  ci_testing/models/encounter.sql
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/encounter.sql
  integration_tests/docs_generate/models/medical_claim.sql
  integration_tests/docs_generate/models/pharmacy_claim.sql
  integration_tests/models/encounter.sql
  models/ahrq_measures/pqi/final/ahrq_measures__pqi_summary.sql
  models/ahrq_measures/pqi/staging/ahrq_measures__stg_pqi_inpatient_encounter.sql
  models/claims_preprocessing/acute_inpatient/final/acute_inpatient__summary.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__data_quality_summary.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__first_claim_values.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__institutional_claims.sql
  models/claims_preprocessing/acute_inpatient/intermediate/acute_inpatient__institutional_encounter_id.sql
  models/claims_preprocessing/acute_inpatient/staging/acute_inpatient__stg_medical_claim.sql
  models/claims_preprocessing/emergency_department/final/emergency_department__summary.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_first_claim_values.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_institutional_claims.sql
  models/claims_preprocessing/emergency_department/intermediate/emergency_department__int_institutional_encounter_id.sql
  models/claims_preprocessing/emergency_department/staging/emergency_department__stg_medical_claim.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__medical_claim.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_admit_source_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_admit_source_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_admit_type_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_admit_type_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_apr_drg_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_apr_drg_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_bill_type_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_bill_type_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_discharge_disposition_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_discharge_disposition_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_medical_npi_normalize.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_ms_drg_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_ms_drg_voting.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_place_of_service_normalize.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_revenue_center_normalize.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_undetermined_claim_type.sql
  models/core/staging/core__stg_claims_encounter.sql
  models/core/staging/core__stg_claims_location.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
  models/core/staging/core__stg_claims_practitioner.sql
  models/core/staging/core__stg_claims_procedure.sql
  models/core/staging/core__stg_clinical_encounter.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_institutional_header_fail_details.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_inst_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_invalid_npi.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_prof_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_professional_header_fail_details.sql
  models/data_quality/data_quality_models.yml
  models/ed_classification/final/ed_classification__summary.sql
  models/ed_classification/staging/ed_classification__stg_encounter.sql
  models/readmissions/final/readmissions__encounter_augmented.sql
  models/readmissions/final/readmissions__readmission_summary.sql
  models/readmissions/intermediate/readmissions__encounter.sql
  models/readmissions/intermediate/readmissions__encounter_with_ccs.sql
  models/readmissions/staging/readmissions__stg_core__encounter.sql
Labels: breaking-change, enhancement

#509 Flagging claims with enrollment
  integration_tests/dbt_project.yml
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/core/final/core__member_months.sql
  models/core/staging/core__stg_claims_encounter.sql
  models/core/staging/core__stg_claims_medical_claim.sql
Labels: enhancement

#511 Pharmacy updates: NPIs added to Core and NPIs field renamed to ID
  integration_tests/seeds/medical_claim_seed.csv
  integration_tests/seeds/pharmacy_claim_seed.csv
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
  models/core/staging/core__stg_claims_condition.sql
  models/core/staging/core__stg_claims_eligibility.sql
  models/core/staging/core__stg_claims_encounter.sql
  models/core/staging/core__stg_claims_location.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_patient.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
  models/core/staging/core__stg_claims_practitioner.sql
  models/core/staging/core__stg_claims_procedure.sql
  models/data_quality/claims_preprocessing/final/data_quality__claims_preprocessing_summary.sql
  models/data_quality/claims_preprocessing/final/data_quality__claims_preprocessing_test_detail.sql
  models/data_quality/claims_preprocessing/final/data_quality__claims_preprocessing_test_result.sql
  models/data_quality/claims_preprocessing/final/data_quality__claims_preprocessing_use_case.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_claim_type_mapping_failures.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_claim_type_unmapped.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_eligibility_denominators.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_eligibility_duplicates.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_eligibility_invalid_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_eligibility_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_eligibility_plausibility.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_institutional_header_fail_details.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_dates.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_dates_inst.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_denominators.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_duplicates.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_inst_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_invalid_npi.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_invalid_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_line_numbers.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_plausibility.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_medical_claim_prof_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_pharmacy_claim_duplicates.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_pharmacy_claim_line_numbers.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_pharmacy_claim_missing_values.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_pharmacy_header_fail_details.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_professional_header_fail_details.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_detail_stage_eligibility.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_detail_stage_medical_claim.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_detail_stage_pharmacy_claim.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_result_stage_eligibility.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_result_stage_medical_claim.sql
  models/data_quality/claims_preprocessing/intermediate/data_quality__claims_preprocessing_test_result_stage_pharmacy_claim.sql
  models/data_quality/data_quality_models.yml
  models/pharmacy/final/pharmacy__pharmacy_claim_expanded.sql
  models/pharmacy/staging/pharmacy__stg_pharmacy_claim.sql
Labels: bug

#513 Add pharmacy charge amount
  integration_tests/dbt_project.yml
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/pharmacy_claim_seed.csv
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_pharmacy_claim.sql
  models/core/core_models.yml
  models/core/staging/core__stg_claims_pharmacy_claim.sql
Labels: breaking-change

#516 Add rendering and billing TIN
  integration_tests/seeds/medical_claim_seed.csv
  models/claims_preprocessing/normalized_input/final/normalized_input__medical_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_medical_claim.sql
  models/core/core_models.yml
  models/core/staging/core__stg_claims_medical_claim.sql
  seeds/value_sets/data_quality/data_quality__seeds.yml
Labels: breaking-change

#518 Fixing ref in emergency_department__summary.sql to reference staging table rather than input_layer.
  models/claims_preprocessing/emergency_department/final/emergency_department__summary.sql
Labels: bug

#519 BUGFIX: tuva_schema_prefix
  models/ahrq_measures/pqi/pqi_models.yml
Labels: bug
