Repository tuva-health/tuva, pull requests merged in 2024-11, with the labels that each got.

#648 fixing divide by 0 issue
  models/data_quality/dqi/mart_review/final/mart_review__pharmacy.sql
Labels: bug

#650 Changes to load synthetic data for fabric
  integration_tests/dbt_project.yml
  integration_tests/macros/limit_zero.sql
  integration_tests/models/condition.sql
  integration_tests/models/encounter.sql
  integration_tests/models/location.sql
  integration_tests/models/medication.sql
  integration_tests/models/patient.sql
  integration_tests/models/practitioner.sql
  integration_tests/models/procedure.sql
  integration_tests/seeds/_seeds.yml
Labels: enhancement

#640 postgreql safe data_quality__eligibility_death_flag
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_death_flag.sql
Labels: community

#682 Add optional variable for bucket name
  dbt_project.yml
Labels: enhancement
