Repository tuva-health/tuva, pull requests merged in 2024-12, with the labels that each got.

#683 Resolves #672 safe_cast() appears not to map to try_cast() in Databricks
  models/claims_preprocessing/service_category/intermediate/service_category__office_based_surgery_professional.sql
Labels: bug, community

#627 add monthly patient risk models
  models/cms_hcc/cms_hcc_models.yml
  models/cms_hcc/final/cms_hcc__patient_risk_factors.sql
  models/cms_hcc/final/cms_hcc__patient_risk_factors_monthly.sql
  models/cms_hcc/final/cms_hcc__patient_risk_scores.sql
  models/cms_hcc/final/cms_hcc__patient_risk_scores_monthly.sql
  models/cms_hcc/intermediate/cms_hcc__int_demographic_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_disabled_interaction_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_disease_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_disease_interaction_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_eligible_conditions.sql
  models/cms_hcc/intermediate/cms_hcc__int_enrollment_interaction_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_hcc_count_factors.sql
  models/cms_hcc/intermediate/cms_hcc__int_hcc_hierarchy.sql
  models/cms_hcc/intermediate/cms_hcc__int_hcc_mapping.sql
  models/cms_hcc/intermediate/cms_hcc__int_members.sql
  models/cms_hcc/intermediate/cms_hcc__int_monthly_collection_dates.sql
Labels: breaking-change, community, enhancement

#688 Remove quality measures
  models/quality_measures/final/quality_measures__summary_long.sql
  models/quality_measures/final/quality_measures__summary_wide.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055__performance_period.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055_denominator.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055_exclusions.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055_long.sql
  models/quality_measures/intermediate/cbe0055_diabetes_eye_exam/quality_measures__int_cbe0055_numerator.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101__performance_period.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_denominator.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_exclusions.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_long.sql
  models/quality_measures/intermediate/cbe0101_falls_plan_of_care/quality_measures__int_cbe0101_numerator.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236__performance_period.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_denominator.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_exclude_procedures_observations.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_exclusions.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_long.sql
  models/quality_measures/intermediate/cqm236_controlling_blood_pressure/quality_measures__int_cqm236_numerator.sql
  models/quality_measures/intermediate/cqm48_urinary_incontinence/quality_measures__int_cqm48__performance_period.sql
  models/quality_measures/intermediate/cqm48_urinary_incontinence/quality_measures__int_cqm48_denominator.sql
  models/quality_measures/intermediate/cqm48_urinary_incontinence/quality_measures__int_cqm48_exclusions.sql
  models/quality_measures/intermediate/cqm48_urinary_incontinence/quality_measures__int_cqm48_long.sql
  models/quality_measures/intermediate/cqm48_urinary_incontinence/quality_measures__int_cqm48_numerator.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034__performance_period.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_denominator.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_colectomy_cancer.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclusions.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_long.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_numerator.sql
  models/quality_measures/intermediate/nqf0041_influenza_immunization/quality_measures__int_nqf0041__performance_period.sql
  models/quality_measures/intermediate/nqf0041_influenza_immunization/quality_measures__int_nqf0041_denominator.sql
  models/quality_measures/intermediate/nqf0041_influenza_immunization/quality_measures__int_nqf0041_exclusions.sql
  models/quality_measures/intermediate/nqf0041_influenza_immunization/quality_measures__int_nqf0041_long.sql
  models/quality_measures/intermediate/nqf0041_influenza_immunization/quality_measures__int_nqf0041_numerator.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053__performance_period.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_denominator.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_exclude_procedures_medications.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_exclusions.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_exclusions_stage_1.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_long.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_numerator.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059__performance_period.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059_denominator.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059_exclusions.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059_long.sql
  models/quality_measures/intermediate/nqf0059_diabetes_hemoglobin_a1c/quality_measures__int_nqf0059_numerator.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372__performance_period.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_denominator.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_mastectomy.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclusions.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_long.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_numerator.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097__performance_period.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097_denominator.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097_exclusions.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097_long.sql
  models/quality_measures/intermediate/nqf_0097_medication_reconciliation_post_discharge/quality_measures__int_nqf0097_numerator.sql
  models/quality_measures/quality_measures_models.yml
Labels: breaking-change

#689 Add new fields to provider terminology seeds
  dbt_project.yml
  seeds/terminology/terminology__provider.csv
  seeds/terminology/terminology_seeds.yml
Labels: breaking-change, enhancement
