Repository tuva-health/tuva, pull requests merged in 2024-02, with the labels that each got.

#365 quality measures bug fixes
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  models/quality_measures/final/quality_measures__summary_counts.sql
  models/quality_measures/final/quality_measures__summary_long.sql
  models/quality_measures/final/quality_measures__summary_wide.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_exclude_advanced_illness.sql
  models/quality_measures/intermediate/nqf0034_colorectal_cancer_screening/quality_measures__int_nqf0034_long.sql
  models/quality_measures/intermediate/nqf2372_breast_cancer_screening/quality_measures__int_nqf2372_exclude_advanced_illness.sql
Labels: bug

#375 Add medication terminology files
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  seeds/terminology/terminology__ndc.csv
  seeds/terminology/terminology__rxnorm_to_atc.csv
  seeds/terminology/terminology_seeds.yml
Labels: enhancement

#380 Update unique key logic for patient risk score snapshot
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  snapshots/cms_hcc/cms_hcc__patient_risk_scores_snapshot.sql
Labels: bug

#392 Add missing tests from data_quality seed for pharmacy claim
  .github/workflows/biweekly_dbt_v1.3.0_bigquery_build_full_refresh.yml
  .github/workflows/outside_contributor_dbt_v1.4.6_all_build_full_refresh.yml
  seeds/value_sets/data_quality/data_quality__test_catalog.csv
Labels: bug

#396 Update core__stg_clinical_lab_result.sql
  models/core/staging/core__stg_clinical_lab_result.sql
Labels: bug

#397 added comma to select statement
  dbt_project.yml
  models/quality_measures/staging/quality_measures__stg_core__encounter.sql
Labels: bug

#402 Add logic to integration_tests for new synthetic observation data
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/models/observation.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/observation_seed.csv
Labels: enhancement

#403 Add logic to release yml for non-labeled PRs
  .github/release.yml
Labels: ignore-for-release
