Repository tuva-health/tuva, pull requests merged in 2024-08, with the labels that each got.

#560 Adding RBCS as new seed file to the tuva project
  dbt_project.yml
  seeds/value_sets/rbcs/rbcs__hcpcs_to_rbcs.csv
  seeds/value_sets/rbcs/rbcs_seeds.yml
Labels: terminology, enhancement

#564 Doc updates
  integration_tests/docs_generate/dbt_project.yml
  integration_tests/docs_generate/models/_models.yml
  models/ahrq_measures/pqi/pqi_models.yml
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/cms_hcc/cms_hcc_models.yml
  models/core/core_models.yml
  models/ed_classification/ed_classification_models.yml
  models/pharmacy/pharmacy_models.yml
  models/readmissions/readmissions_models.yml
Labels: docs, enhancement

#568 Fixing PMPM prep join issue
  models/financial_pmpm/final/financial_pmpm__pmpm_prep.sql
Labels: bug

#563 moving rbcs value set to claims_preprocessing mart
  dbt_project.yml
  seeds/terminology/terminology__hcpcs_to_rbcs.csv
  seeds/terminology/terminology_seeds.yml
  seeds/value_sets/rbcs/rbcs__hcpcs_to_rbcs.csv
  seeds/value_sets/rbcs/rbcs_seeds.yml
Labels: bug, enhancement

#572 Nqf0053 fabric
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_exclusions.sql
  models/quality_measures/intermediate/nqf0053_osteoporosis_management_in_women_who_had_a_fracture/quality_measures__int_nqf0053_exclusions_stage_1.sql
  models/quality_measures/quality_measures_models.yml
Labels: bug

#574 Fabric plan macro
  macros/quote_column.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__eligibility.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__medical_claim.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_eligibility_dates_normalize.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_undetermined_claim_type.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_eligibility.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_medical_claim.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_pharmacy_claim.sql
  models/cms_hcc/staging/cms_hcc__stg_core__member_months.sql
  models/core/final/core__member_months.sql
  models/core/staging/core__stg_claims_eligibility.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
  models/data_quality/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_plan.sql
  models/data_quality/intermediate/atomic_checks/claims/medical/data_quality__claim_plan.sql
  models/data_quality/intermediate/atomic_checks/claims/pharmacy/data_quality__pharmacy_plan.sql
  models/financial_pmpm/final/financial_pmpm__pmpm_payer_plan.sql
  models/financial_pmpm/final/financial_pmpm__pmpm_prep.sql
  models/financial_pmpm/financial_pmpm_models.yml
  models/financial_pmpm/intermediate/financial_pmpm__patient_spend_with_service_categories.sql
  models/financial_pmpm/intermediate/financial_pmpm__service_category_1_allowed_pivot.sql
  models/financial_pmpm/intermediate/financial_pmpm__service_category_1_paid_pivot.sql
  models/financial_pmpm/intermediate/financial_pmpm__service_category_2_allowed_pivot.sql
  models/financial_pmpm/intermediate/financial_pmpm__service_category_2_paid_pivot.sql
  models/financial_pmpm/staging/financial_pmpm__stg_eligibility.sql
  models/financial_pmpm/staging/financial_pmpm__stg_medical_claim.sql
  models/financial_pmpm/staging/financial_pmpm__stg_pharmacy_claim.sql
Labels: enhancement

#575 adding drg weights to terminology
  dbt_project.yml
  seeds/terminology/terminology__ms_drg_weights_los.csv
  seeds/terminology/terminology_seeds.yml
Labels: breaking-change, enhancement

#573 adding los groups to table for PBI
  models/data_quality/mart_review/final/mart_review__inpatient.sql
Labels: breaking-change, enhancement

#579 BUG FIX: CMS Chronic Conditions staging references
  models/chronic_conditions/cms_chronic_conditions_models.yml
  models/chronic_conditions/intermediate/chronic_conditions__cms_chronic_conditions_all.sql
  models/chronic_conditions/intermediate/chronic_conditions__cms_chronic_conditions_hiv_aids.sql
  models/chronic_conditions/intermediate/chronic_conditions__cms_chronic_conditions_oud.sql
  models/chronic_conditions/staging/cms_chronic_conditions__stg_core__medical_claim.sql
  models/chronic_conditions/staging/cms_chronic_conditions__stg_core__pharmacy_claim.sql
Labels: bug
