Repository tuva-health/tuva, pull requests merged in 2025-02, with the labels that each got.

#705 Mart review plan updates
  dbt_doc_blocks/column_descriptions.md
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_rx_claims_with_enrollment.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/core/core_models.yml
  models/core/final/core__member_months.sql
  models/core/staging/core__stg_claims_medical_claim.sql
  models/core/staging/core__stg_claims_pharmacy_claim.sql
  models/data_quality/dqi/mart_review/final/mart_review__claims_with_enrollment.sql
  models/data_quality/dqi/mart_review/final/mart_review__member_months.sql
  models/data_quality/dqi/mart_review/final/mart_review__service_categories_long.sql
Labels: breaking-change, enhancement

#707 CI/CD Redshift Migration
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
  ci_testing/profiles/redshift/profiles.yml
Labels: ignore-for-release

#719 Bq optimization
  models/claims_preprocessing/encounters/encounter_models.yml
  models/claims_preprocessing/encounters/intermediate/emergency_department/emergency_department__generate_encounter_id.sql
  models/claims_preprocessing/encounters/intermediate/emergency_department/emergency_department__generate_encounter_id_pre_sort.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_diagnosis_code_normalize.sql
  models/data_quality/data_quality_models.yml
Labels: enhancement
