Repository tuva-health/tuva, pull requests merged in 2025-09, with the labels that each got.

#1052 Removing tests and duplicate file_date definitions
  models/core/core_models.yml
Labels: bug

#1059 Patch v0.15.1
  dbt_project.yml
Labels: ignore-for-release

#1060 [Feature] add optional source input for quality measures mart
  ci_testing/dbt_project.yml
  ci_testing/models/_ci_testing__models.yml
  ci_testing/models/_sources.yml
  ci_testing/models/hedis_cql_engine_log.sql
  ci_testing/models/hedis_measure_report.sql
  ci_testing/seeds/_seeds.yml
  ci_testing/seeds/hedis_cql_engine_log_seed.csv
  ci_testing/seeds/hedis_measure_report_seed.csv
  dbt_doc_blocks/column_descriptions.md
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/dbt_project.yml
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/hedis_cql_engine_log.sql
  integration_tests/docs_generate/models/hedis_measure_report.sql
  integration_tests/models/_integration_tests__models.yml
  integration_tests/models/_sources.yml
  integration_tests/models/hedis_cql_engine_log.sql
  integration_tests/models/hedis_measure_report.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/hedis_cql_engine_log_seed.csv
  integration_tests/seeds/hedis_measure_report_seed.csv
  macros/cross_database_utils/load_seed.sql
  models/quality_measures/hedis_dqm_results/final/quality_measures__hedis_cql_engine_log.sql
  models/quality_measures/hedis_dqm_results/final/quality_measures__hedis_summary_counts.sql
  models/quality_measures/hedis_dqm_results/final/quality_measures__hedis_summary_long.sql
  models/quality_measures/hedis_dqm_results/hedis_dqm_results_models.yml
  models/quality_measures/hedis_dqm_results/intermediate/quality_measures__int_hedis_cql_engine_log.sql
  models/quality_measures/hedis_dqm_results/intermediate/quality_measures__int_hedis_measure_normalize.sql
  models/quality_measures/hedis_dqm_results/intermediate/quality_measures__int_hedis_measure_report.sql
  models/quality_measures/hedis_dqm_results/staging/quality_measures__stg_hedis_cql_engine_log.sql
  models/quality_measures/hedis_dqm_results/staging/quality_measures__stg_hedis_measure_report.sql
  snapshots/quality_measures/quality_measures__hedis_cql_engine_log_snapshot.sql
  snapshots/quality_measures/quality_measures__hedis_summary_counts_snapshot.sql
  snapshots/quality_measures/quality_measures__hedis_summary_long_snapshot.sql
Labels: enhancement

#1081 update input_layer__medical_claim.yml unique value count test so null…
  models/input_layer/input_layer__medical_claim.yml
Labels: bug
