Repository tuva-health/tuva, pull requests merged in 2025-05, with the labels that each got.

#786 Updated contributing instructions for running and linting
  CONTRIBUTING.md
Labels: enhancement

#784 Move member_month_key calculation to norm_input_elig. Adjust claims_e…
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_rx_claims_with_enrollment.sql
  models/claims_preprocessing/normalized_input/final/normalized_input__eligibility.sql
  models/core/final/core__member_months.sql
Labels: bug

#789 Provider terminology fields addition
  dbt_project.yml
  seeds/terminology/terminology__provider.csv
  seeds/terminology/terminology_seeds.yml
Labels: terminology, enhancement

#821 Updated error message to be more informative
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
Labels: bug

#842 Fix deprecation warning in encounter_type seed
  seeds/terminology/terminology_seeds.yml
Labels: bug

#852 Fix join clause in `data_quality__encounters_cost_and_utilization`
  models/data_quality/intermediate/data_quality__encounters_cost_and_utilization.sql
Labels: bug, community

#858 Provider attribution have patient id when disabled.
  models/input_layer/input_layer__provider_attribution.sql
Labels: bug, v0.14.12

#853 Icd10 column descriptions
  seeds/terminology/terminology_seeds.yml
Labels: enhancement, v0.14.12

#859 Terminology Update: NDC, RXNORM_TO_ATC, RXNORM_BRAND_GENERIC, Valueset: RXNORM_GENERIC_AVAILABLE
  dbt_project.yml
Labels: v0.14.12

#860 Terminology Update: Provider and Other Provider Taxonomy - May 2025
  dbt_project.yml
Labels: v0.14.12

#861 Terminology Update: APR-DRG, MS-DRG, ICD10CM, ICD10PCS, HCPCS Level 2
  dbt_project.yml
Labels: v0.14.12

#870 Revert "Fix redshift actions to compile instead of build (#824)"
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
Labels: bug, v0.14.12

#872 Updating multiple values tests to have a floor of 0 as not null tests should check for nulls
  models/input_layer/input_layer__eligibility.yml
  models/input_layer/input_layer__medical_claim.yml
Labels: bug, v0.14.12

#863 Add fhir_preprocessing data mart
  dbt_doc_blocks/column_descriptions.md
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/dbt_project.yml
  macros/cross_database_utils/create_json_object.sql
  macros/cross_database_utils/length.sql
  models/fhir_preprocessing/fhir_preprocessing_models.yml
  models/fhir_preprocessing/final/fhir_preprocessing__condition.sql
  models/fhir_preprocessing/final/fhir_preprocessing__coverage.sql
  models/fhir_preprocessing/final/fhir_preprocessing__explanation_of_benefit.sql
  models/fhir_preprocessing/final/fhir_preprocessing__medication_dispense.sql
  models/fhir_preprocessing/final/fhir_preprocessing__observation.sql
  models/fhir_preprocessing/final/fhir_preprocessing__patient.sql
  models/fhir_preprocessing/final/fhir_preprocessing__procedure.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_coverage.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_coverage_type.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_lab_result.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_diagnosis.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_eob.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_item.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_item_adjudication.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_item_modifier.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_procedure.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_supporting_info.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_medical_claim_total.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_observation.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_pharmacy_claim_eob.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_pharmacy_claim_item.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_pharmacy_claim_item_adjudication.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_pharmacy_claim_supporting_info.sql
  models/fhir_preprocessing/intermediate/fhir_preprocessing__int_pharmacy_claim_total.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__condition.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__eligibility.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__encounter.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__lab_result.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__medical_claim.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__medication.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__observation.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__patient.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__pharmacy_claim.sql
  models/fhir_preprocessing/staging/fhir_preprocessing__stg_core__procedure.sql
Labels: enhancement, v0.14.13
