Repository tuva-health/tuva, pull requests merged in 2025-06, with the labels that each got.

#890 Add duckdb support to create_json_object macro
  macros/cross_database_utils/create_json_object.sql
Labels: enhancement

#885 Fix enrollment being exploded to row per member-month. Adjust testing on PK.
  .gitignore
  macros/cross_database_utils/create_json_object.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_rx_claims_with_enrollment.sql
  models/claims_preprocessing/claims_enrollment/claims_enrollment__member_months.sql
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/claims_preprocessing/normalized_input/final/normalized_input__eligibility.sql
  models/core/core_models.yml
  models/core/final/core__member_months.sql
  models/core/staging/core__stg_claims_member_months.sql
Labels: bug, v0.14.13

#895 Rename "header_flag" column to "billable_code_flag" in icd_10_cm terminology
  dbt_project.yml
Labels: v0.15.0

#909 Split SQL files to reduce memory load
  models/data_quality/dqi/dqi_models.yml
  models/data_quality/dqi/intermediate/union_processing/clinical/data_quality__data_quality_clinical_detail.sql
  models/data_quality/dqi/intermediate/union_processing/clinical/data_quality__data_quality_clinical_detail_base.sql
Labels: enhancement, v0.14.14

#908 Update elementary version
  packages.yml
Labels: enhancement, v0.14.14

#878 Update github workflows: add testing for new data mart, add release workflow, remove old workflow
  .github/workflows/add_issues_to_project.yml
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/release.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
Labels: ignore-for-release, v0.14.14

#896 Terminology ms_drg_weights_los schema update
  dbt_project.yml
  models/data_quality/dqi/mart_review/final/mart_review__inpatient.sql
  seeds/terminology/terminology__ms_drg_weights_los.csv
  seeds/terminology/terminology_seeds.yml
Labels: v0.15.0

#931 Fixing MDC value bug
  models/claims_preprocessing/service_category/intermediate/service_category__acute_inpatient_institutional_maternity.sql
Labels: bug, v0.14.15

#928 Change line level claim date to header level
  models/claims_preprocessing/claims_enrollment/claims_enrollment__flag_claims_with_enrollment.sql
Labels: enhancement, v0.14.15

#933 932 if encounters between claims and clinical datasets overlap ie adt both encounter get thrown out in readmissions
  models/readmissions/intermediate/readmissions__encounter.sql
  models/readmissions/intermediate/readmissions__encounter_data_quality.sql
  models/readmissions/intermediate/readmissions__encounter_overlap.sql
  models/readmissions/intermediate/readmissions__readmission_crude.sql
  models/readmissions/readmissions_models.yml
  models/readmissions/staging/readmissions__stg_core__encounter.sql
Labels: enhancement, v0.14.15

#929 Add enhancements for CI Testing data
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
  ci_testing/dbt_project.yml
  ci_testing/macros/limit_zero.sql
  ci_testing/models/_ci_testing__models.yml
  ci_testing/models/_sources.yml
  ci_testing/models/condition.sql
  ci_testing/models/eligibility.sql
  ci_testing/models/encounter.sql
  ci_testing/models/lab_result.sql
  ci_testing/models/location.sql
  ci_testing/models/medical_claim.sql
  ci_testing/models/medication.sql
  ci_testing/models/observation.sql
  ci_testing/models/patient.sql
  ci_testing/models/pharmacy_claim.sql
  ci_testing/models/practitioner.sql
  ci_testing/models/procedure.sql
  ci_testing/models/provider_attribution.sql
  ci_testing/profiles/fabric/profiles.yml
  ci_testing/profiles/redshift/profiles.yml
  ci_testing/seeds/_seeds.yml
  ci_testing/seeds/eligibility_seed.csv
  ci_testing/seeds/medical_claim_seed.csv
  ci_testing/seeds/pharmacy_claim_seed.csv
Labels: enhancement

#949 Fix redshift CI tests
  .github/workflows/outside_contributor_dbt_v1.8.6.yml
  .github/workflows/tuva_internal_dbt_v1.8.6.yml
Labels: bug

#952 Fix PMPM Prep pk
  models/financial_pmpm/financial_pmpm_models.yml
Labels: bug, v0.14.16

#955 Adjust metadata schema to account for target schema config.
  macros/metadata/tuva_invocations.sql
Labels: bug
