Repository tuva-health/tuva, pull requests merged in 2025-08, with the labels that each got.

#1012 Patch release v0.14.18
  dbt_project.yml
Labels: ignore-for-release

#990 Fix: Dx codes not flowing to core.condition when missing in terminology
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/claims_preprocessing/normalized_input/final/normalized_input__medical_claim.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_diagnosis_code_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_diagnosis_code_intermediate.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_diagnosis_code_normalize.sql
  models/core/staging/core__stg_claims_condition.sql
Labels: breaking-change

#1028 Add claim type distribution check
  tests/claim_type_not_only_undetermined_check.sql
Labels: enhancement

#981 [Breaking Change] Immunization Table addition from Input to Core layer
  ci_testing/dbt_project.yml
  ci_testing/models/_ci_testing__models.yml
  ci_testing/models/_sources.yml
  ci_testing/models/immunization.sql
  ci_testing/seeds/_seeds.yml
  ci_testing/seeds/immunization_seed.csv
  dbt_doc_blocks/column_descriptions.md
  dbt_project.yml
  integration_tests/dbt_project.yml
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/immunization.sql
  integration_tests/models/_integration_tests__models.yml
  integration_tests/models/_sources.yml
  integration_tests/models/immunization.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/immunization_seed.csv
  models/core/core_models.yml
  models/core/final/core__immunization.sql
  models/core/staging/core__stg_clinical_immunization.sql
  models/data_quality/dqi/dqi_models.yml
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_body_site.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_data_source.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_encounter_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_immunization_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_location_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_lot_number.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_normalized_code.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_normalized_code_type.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_normalized_description.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_normalized_dose.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_occurrence_date.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_patient_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_person_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_practitioner_id.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_source_code.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_source_code_type.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_source_description.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/immunization/data_quality__immunization_source_dose.sql
  models/data_quality/dqi/intermediate/concepts/data_quality__unique_value_examples.sql
  models/data_quality/dqi/intermediate/concepts/primary_keys/data_quality__primary_keys_immunization_immunization_id.sql
  models/data_quality/dqi/intermediate/union_processing/clinical/data_quality__data_quality_clinical_detail_union.sql
  models/data_quality/dqi/stage/data_quality__stg_immunization.sql
  models/input_layer/input_layer__immunization.sql
  models/input_layer/input_layer__immunization.yml
  models/normalize/_models.yml
  models/normalize/normalize__unmapped_immunization.sql
  models/normalize/staging/normalize__stg_unmapped_immunization.sql
  seeds/terminology/terminology__act_site.csv
  seeds/terminology/terminology__cvx.csv
  seeds/terminology/terminology__immunization_route_code.csv
  seeds/terminology/terminology__immunization_status.csv
  seeds/terminology/terminology__immunization_status_reason.csv
  seeds/terminology/terminology_seeds.yml
Labels: breaking-change, v0.15.0

#966 Move some testing from older dqi into newer dqi
  .github/workflows/outside_contributor_dbt_v1.9.4.yml
  .github/workflows/tuva_internal_dbt_v1.9.4.yml
  README.md
  dbt_project.yml
  macros/utils/is_fabric.sql
  models/chronic_conditions/cms_chronic_conditions_models.yml
  models/chronic_conditions/tuva_chronic_conditions_models.yml
  models/claims_preprocessing/service_category/service_category_models.yml
  models/cms_hcc/cms_hcc_models.yml
  models/core/core_models.yml
  models/core/staging/core__stg_clinical_encounter.sql
  models/data_quality/data_quality__exploratory_charts.sql
  models/data_quality/data_quality__testing_summary.sql
  models/data_quality/data_quality_models.yml
  models/data_quality/dqi/dqi_models.yml
  models/data_quality/dqi/final/data_quality__exploratory_charts.sql
  models/financial_pmpm/financial_pmpm_models.yml
  models/input_layer/input_layer__condition.yml
  models/input_layer/input_layer__eligibility.yml
  models/input_layer/input_layer__encounter.yml
  models/input_layer/input_layer__lab_result.yml
  models/input_layer/input_layer__location.yml
  models/input_layer/input_layer__medical_claim.yml
  models/input_layer/input_layer__medication.yml
  models/input_layer/input_layer__observation.yml
  models/input_layer/input_layer__patient.yml
  models/input_layer/input_layer__pharmacy_claim.yml
  models/input_layer/input_layer__practitioner.yml
  models/input_layer/input_layer__procedure.yml
  models/input_layer/input_layer__provider_attribution.yml
  models/quality_measures/quality_measures_models.yml
  models/readmissions/readmissions_models.yml
  tests/generic/dbt_expectations_tests.sql
  tests/generic/test_warn_if_null_percentage_above_zero.sql
Labels: enhancement

#1035 Fix: Procedure codes not flowing to core.procedure when missing in terminology
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_procedure_code_final.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_procedure_code_intermediate.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_procedure_code_normalize.sql
  models/claims_preprocessing/normalized_input/intermediate/normalized_input__int_procedure_code_voting.sql
  models/core/staging/core__stg_claims_procedure.sql
Labels: breaking-change, v0.15.0

#1032 #946 Addition of fields to the core.patient table
  ci_testing/dbt_project.yml
  ci_testing/models/patient.sql
  ci_testing/seeds/_seeds.yml
  ci_testing/seeds/eligibility_seed.csv
  dbt_doc_blocks/column_descriptions.md
  integration_tests/docs_generate/models/_models.yml
  integration_tests/docs_generate/models/patient.sql
  integration_tests/models/patient.sql
  integration_tests/seeds/_seeds.yml
  integration_tests/seeds/eligibility_seed.csv
  models/claims_preprocessing/claims_preprocessing_models.yml
  models/claims_preprocessing/normalized_input/final/normalized_input__eligibility.sql
  models/claims_preprocessing/normalized_input/staging/normalized_input__stg_eligibility.sql
  models/core/core_models.yml
  models/core/staging/core__stg_claims_patient.sql
  models/core/staging/core__stg_clinical_patient.sql
  models/data_quality/dqi/dqi_models.yml
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_email.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_ethnicity.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_middle_name.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_name_suffix.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/patient/data_quality__patient_email.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/patient/data_quality__patient_ethnicity.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/patient/data_quality__patient_middle_name.sql
  models/data_quality/dqi/intermediate/atomic_checks/clinical/patient/data_quality__patient_name_suffix.sql
  models/data_quality/dqi/intermediate/union_processing/claims/data_quality__data_quality_claims_detail_union.sql
  models/data_quality/dqi/intermediate/union_processing/clinical/data_quality__data_quality_clinical_detail_union.sql
  models/input_layer/input_layer__eligibility.yml
  models/input_layer/input_layer__patient.yml
Labels: breaking-change, v0.15.0

#1038 Update seed paths v0.15 & fix doc-generate workflow
  .github/workflows/generate_and_deploy_dbt_docs.yml
  ci_testing/dbt_project.yml
  dbt_project.yml
Labels: ignore-for-release
