Repository tuva-health/tuva, pull requests merged in 2025-07, with the labels that each got.

#958 Patch release v0.14.16
  .github/pull_request_template.md
  dbt_project.yml
Labels: ignore-for-release

#961 Update LOINC terminology
  dbt_project.yml
Labels: enhancement

#964 Release patch 0.14.17
  dbt_project.yml
Labels: ignore-for-release

#976 Fixing data type inconsistency
  models/core/core_models.yml
Labels: docs

#977 Add HTML data quality dashboard
  ui/data_quality_dashboard.html
Labels: enhancement

#971 970 | Creating de-duplication logic for patients in both claims and clinical
  models/core/final/core__patient.sql
Labels: bug, v0.14.17

#997 Update accepted values on procedure code type
  models/input_layer/input_layer__medical_claim.yml
Labels: bug

#999 Add missing provider fields to dbt docs
  seeds/terminology/terminology_seeds.yml
Labels: bug
