Repository tuva-health/tuva, pull requests merged in 2025-04, with the labels that each got.

#753 Disambiguate `tuva_last_run`, there are issues when input layer models provide this column
  models/data_quality/dqi/intermediate/atomic_checks/claims/medical/data_quality__claim_claim_line_end_date.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/medical/data_quality__claim_claim_line_start_date.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/medical/data_quality__claim_paid_date.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/pharmacy/data_quality__pharmacy_dispensing_date.sql
  models/data_quality/dqi/intermediate/atomic_checks/claims/pharmacy/data_quality__pharmacy_paid_date.sql
Labels: bug

#760 Fixed seed loading for DuckDB + added rows loaded log message.
  macros/load_seed.sql
Labels: bug

#765 Update testing in `patient` in input layer
  models/core/core_models.yml
  models/data_quality/dqi/intermediate/atomic_checks/claims/eligibility/data_quality__eligibility_death_flag.sql
  models/input_layer/input_layer__patient.yml
Labels: bug, community, docs

#767 Fix column typings in medical claim seed
  integration_tests/seeds/_seeds.yml
Labels: bug, community

#773 Added check for readmissions enabled for mart review
  models/data_quality/dqi/mart_review/final/mart_review__readmissions.sql
  models/readmissions/intermediate/readmissions__index_admission.sql
Labels: bug

#782 Update README in `integration_tests`
  CONTRIBUTING.md
  integration_tests/README.md
Labels: docs

#788 swapping coalesce for case
  models/claims_preprocessing/normalized_input/final/normalized_input__pharmacy_claim.sql
Labels: bug
